spring.application.name=e-commerce

# H2 Database (resets when the app stops)
# spring.datasource.url=jdbc:h2:mem:testdb
# spring.datasource.driverClassName=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=
# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console
#######################################


# Datasource (conexión básica)

spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_db?useSSL=false&serverTimezone=UTC

#usuario y contraseña de la db
spring.datasource.username=root
spring.datasource.password=

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de Hibernate/JPA
spring.jpa.hibernate.ddl-auto=update 

spring.jpa.show-sql=true 
# Muestra en la consola las sentencias SQL generadas por Hibernate. (en desarrollo)


spring.jpa.properties.hibernate.format_sql=true
# Formatea el SQL para mejor legibilidad

# Hibernate 6+ autodetecta el dialecto según la conexión JDBC, no hace falta declararlo a mano.

